default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch("PG_USER") { 'postgres' } %>
  password: <%= ENV.fetch("PG_PASSWORD") { 'postgres' } %>
  host: <%= ENV.fetch("PG_HOST") { 'localhost' } %>
  port: <%= ENV.fetch("PG_PORT") { 5432 } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { 'steam_stats_app_development' } %>

test:
  <<: *default
  database: steam_stats_app_test

production:
  <<: *default
  database: steam_stats_app_production
  username: steam_stats_app
  password: <%= ENV['STEAM_STATS_APP_DATABASE_PASSWORD'] %>
